// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbozuvsygO4aa7Ge5isIUAe4S2Ar5y3Q8',
    appId: '1:877875890156:web:e26f962ebd8a65749822c9',
    messagingSenderId: '877875890156',
    projectId: 'ionic-3b965',
    authDomain: 'ionic-3b965.firebaseapp.com',
    storageBucket: 'ionic-3b965.firebasestorage.app',
    measurementId: 'G-ZMRFEHSYEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJmu5b7ld0pQNt9lrGNfANXeHG9UxSvAI',
    appId: '1:877875890156:android:bb83cb018fdfa1289822c9',
    messagingSenderId: '877875890156',
    projectId: 'ionic-3b965',
    storageBucket: 'ionic-3b965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx_g1P5RA377Z8uvWPikIfspVRC3Up43I',
    appId: '1:877875890156:ios:7fc7483c07382af49822c9',
    messagingSenderId: '877875890156',
    projectId: 'ionic-3b965',
    storageBucket: 'ionic-3b965.firebasestorage.app',
    iosBundleId: 'com.example.ionic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx_g1P5RA377Z8uvWPikIfspVRC3Up43I',
    appId: '1:877875890156:ios:7fc7483c07382af49822c9',
    messagingSenderId: '877875890156',
    projectId: 'ionic-3b965',
    storageBucket: 'ionic-3b965.firebasestorage.app',
    iosBundleId: 'com.example.ionic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbozuvsygO4aa7Ge5isIUAe4S2Ar5y3Q8',
    appId: '1:877875890156:web:95baa486d8fc855c9822c9',
    messagingSenderId: '877875890156',
    projectId: 'ionic-3b965',
    authDomain: 'ionic-3b965.firebaseapp.com',
    storageBucket: 'ionic-3b965.firebasestorage.app',
    measurementId: 'G-6SPXM8VPN2',
  );
}
