// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/app_settings.dart';
import 'core/models/product_item_model.dart';
import 'features/cart/data/models/cart_local_model.dart';
import 'features/cart/data/models/cart_product_local_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3607200877144655389),
    name: 'AppSettings',
    lastPropertyId: const obx_int.IdUid(4, 400166141050460618),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2235000903107620588),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3020273363963970824),
        name: 'isDarkMode',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7531402249801101902),
        name: 'isFirstTime',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 400166141050460618),
        name: 'isEnableNotification',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4917520937335082264),
    name: 'ProductItemModel',
    lastPropertyId: const obx_int.IdUid(11, 5797003170052896360),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 966944341466508862),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8283118843620508549),
        name: 'productId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3713096769694632708),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2000132989491215905),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7474772174442036108),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5098746854507972654),
        name: 'discount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6170932235725292342),
        name: 'brand',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6448050588353740336),
        name: 'rating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5137092538423693143),
        name: 'stock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7988543289427347089),
        name: 'reviewsCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5797003170052896360),
        name: 'deliveryDays',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3835464390114655718),
    name: 'CartLocalModel',
    lastPropertyId: const obx_int.IdUid(1, 5691012610208271799),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5691012610208271799),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'cartProducts',
        srcEntity: 'CartProductLocalModel',
        srcField: 'cart',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4897410659104016453),
    name: 'CartProductLocalModel',
    lastPropertyId: const obx_int.IdUid(5, 8925298522989421520),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6533046229734852810),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8732864527211450554),
        name: 'productItemId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 4265035882694742800),
        relationTarget: 'ProductItemModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6220068980641815301),
        name: 'returnPolicy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8257699150476720173),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8925298522989421520),
        name: 'cartId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 2193384268094822469),
        relationTarget: 'CartLocalModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 4897410659104016453),
    lastIndexId: const obx_int.IdUid(2, 2193384268094822469),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [6004888736176740058, 7188350132069096693],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      3698640012311869439,
      6549981377943383646,
      3857355228079323238,
      734511456478015182,
      5381042808446140363,
      5730435310936841953,
      4833571906203877201,
      7527000995949110117,
      493140872050341460,
      718348493789171740,
      4211147428576917842,
      5676891121810434691,
      8125824065020373791,
      1345646770767169131,
      7103362176105202485,
      5402707402772965374,
      7815145443919012931,
      6668542210972106335,
      6878443481509638857,
      2762898759230663229,
      319001423601453186,
      1951727307351253626,
      1552060859256502194,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSettings: obx_int.EntityDefinition<AppSettings>(
      model: _entities[0],
      toOneRelations: (AppSettings object) => [],
      toManyRelations: (AppSettings object) => {},
      getId: (AppSettings object) => object.id,
      setId: (AppSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettings object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.isDarkMode);
        fbb.addBool(2, object.isFirstTime);
        fbb.addBool(3, object.isEnableNotification);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final isDarkModeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final isFirstTimeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final isEnableNotificationParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = AppSettings(
          id: idParam,
          isDarkMode: isDarkModeParam,
          isFirstTime: isFirstTimeParam,
          isEnableNotification: isEnableNotificationParam,
        );

        return object;
      },
    ),
    ProductItemModel: obx_int.EntityDefinition<ProductItemModel>(
      model: _entities[1],
      toOneRelations: (ProductItemModel object) => [],
      toManyRelations: (ProductItemModel object) => {},
      getId: (ProductItemModel object) => object.obxId,
      setId: (ProductItemModel object, int id) {
        object.obxId = id;
      },
      objectToFB: (ProductItemModel object, fb.Builder fbb) {
        final productIdOffset = fbb.writeString(object.productId);
        final titleOffset = fbb.writeString(object.title);
        final imageUrlOffset = fbb.writeString(object.imageUrl);
        final brandOffset = fbb.writeString(object.brand);
        fbb.startTable(12);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, productIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, imageUrlOffset);
        fbb.addFloat64(4, object.price);
        fbb.addFloat64(5, object.discount);
        fbb.addOffset(6, brandOffset);
        fbb.addFloat64(7, object.rating);
        fbb.addInt64(8, object.stock);
        fbb.addInt64(9, object.reviewsCount);
        fbb.addInt64(10, object.deliveryDays);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final productIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final discountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final brandParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final ratingParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final stockParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final reviewsCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final deliveryDaysParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = ProductItemModel(
          obxId: obxIdParam,
          productId: productIdParam,
          title: titleParam,
          imageUrl: imageUrlParam,
          price: priceParam,
          discount: discountParam,
          brand: brandParam,
          rating: ratingParam,
          stock: stockParam,
          reviewsCount: reviewsCountParam,
          deliveryDays: deliveryDaysParam,
        );

        return object;
      },
    ),
    CartLocalModel: obx_int.EntityDefinition<CartLocalModel>(
      model: _entities[2],
      toOneRelations: (CartLocalModel object) => [],
      toManyRelations:
          (CartLocalModel object) => {
            obx_int.RelInfo<CartProductLocalModel>.toOneBacklink(
                  5,
                  object.obxId,
                  (CartProductLocalModel srcObject) => srcObject.cart,
                ):
                object.cartProducts,
          },
      getId: (CartLocalModel object) => object.obxId,
      setId: (CartLocalModel object, int id) {
        object.obxId = id;
      },
      objectToFB: (CartLocalModel object, fb.Builder fbb) {
        fbb.startTable(2);
        fbb.addInt64(0, object.obxId);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object =
            CartLocalModel()
              ..obxId = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );
        obx_int.InternalToManyAccess.setRelInfo<CartLocalModel>(
          object.cartProducts,
          store,
          obx_int.RelInfo<CartProductLocalModel>.toOneBacklink(
            5,
            object.obxId,
            (CartProductLocalModel srcObject) => srcObject.cart,
          ),
        );
        return object;
      },
    ),
    CartProductLocalModel: obx_int.EntityDefinition<CartProductLocalModel>(
      model: _entities[3],
      toOneRelations:
          (CartProductLocalModel object) => [object.productItem, object.cart],
      toManyRelations: (CartProductLocalModel object) => {},
      getId: (CartProductLocalModel object) => object.id,
      setId: (CartProductLocalModel object, int id) {
        object.id = id;
      },
      objectToFB: (CartProductLocalModel object, fb.Builder fbb) {
        final returnPolicyOffset = fbb.writeString(object.returnPolicy);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.productItem.targetId);
        fbb.addOffset(2, returnPolicyOffset);
        fbb.addInt64(3, object.quantity);
        fbb.addInt64(4, object.cart.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final returnPolicyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = CartProductLocalModel(
          returnPolicy: returnPolicyParam,
          quantity: quantityParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.productItem.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.productItem.attach(store);
        object.cart.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.cart.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// See [AppSettings.id].
  static final id = obx.QueryIntegerProperty<AppSettings>(
    _entities[0].properties[0],
  );

  /// See [AppSettings.isDarkMode].
  static final isDarkMode = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[1],
  );

  /// See [AppSettings.isFirstTime].
  static final isFirstTime = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[2],
  );

  /// See [AppSettings.isEnableNotification].
  static final isEnableNotification = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[3],
  );
}

/// [ProductItemModel] entity fields to define ObjectBox queries.
class ProductItemModel_ {
  /// See [ProductItemModel.obxId].
  static final obxId = obx.QueryIntegerProperty<ProductItemModel>(
    _entities[1].properties[0],
  );

  /// See [ProductItemModel.productId].
  static final productId = obx.QueryStringProperty<ProductItemModel>(
    _entities[1].properties[1],
  );

  /// See [ProductItemModel.title].
  static final title = obx.QueryStringProperty<ProductItemModel>(
    _entities[1].properties[2],
  );

  /// See [ProductItemModel.imageUrl].
  static final imageUrl = obx.QueryStringProperty<ProductItemModel>(
    _entities[1].properties[3],
  );

  /// See [ProductItemModel.price].
  static final price = obx.QueryDoubleProperty<ProductItemModel>(
    _entities[1].properties[4],
  );

  /// See [ProductItemModel.discount].
  static final discount = obx.QueryDoubleProperty<ProductItemModel>(
    _entities[1].properties[5],
  );

  /// See [ProductItemModel.brand].
  static final brand = obx.QueryStringProperty<ProductItemModel>(
    _entities[1].properties[6],
  );

  /// See [ProductItemModel.rating].
  static final rating = obx.QueryDoubleProperty<ProductItemModel>(
    _entities[1].properties[7],
  );

  /// See [ProductItemModel.stock].
  static final stock = obx.QueryIntegerProperty<ProductItemModel>(
    _entities[1].properties[8],
  );

  /// See [ProductItemModel.reviewsCount].
  static final reviewsCount = obx.QueryIntegerProperty<ProductItemModel>(
    _entities[1].properties[9],
  );

  /// See [ProductItemModel.deliveryDays].
  static final deliveryDays = obx.QueryIntegerProperty<ProductItemModel>(
    _entities[1].properties[10],
  );
}

/// [CartLocalModel] entity fields to define ObjectBox queries.
class CartLocalModel_ {
  /// See [CartLocalModel.obxId].
  static final obxId = obx.QueryIntegerProperty<CartLocalModel>(
    _entities[2].properties[0],
  );

  /// see [CartLocalModel.cartProducts]
  static final cartProducts =
      obx.QueryBacklinkToMany<CartProductLocalModel, CartLocalModel>(
        CartProductLocalModel_.cart,
      );
}

/// [CartProductLocalModel] entity fields to define ObjectBox queries.
class CartProductLocalModel_ {
  /// See [CartProductLocalModel.id].
  static final id = obx.QueryIntegerProperty<CartProductLocalModel>(
    _entities[3].properties[0],
  );

  /// See [CartProductLocalModel.productItem].
  static final productItem =
      obx.QueryRelationToOne<CartProductLocalModel, ProductItemModel>(
        _entities[3].properties[1],
      );

  /// See [CartProductLocalModel.returnPolicy].
  static final returnPolicy = obx.QueryStringProperty<CartProductLocalModel>(
    _entities[3].properties[2],
  );

  /// See [CartProductLocalModel.quantity].
  static final quantity = obx.QueryIntegerProperty<CartProductLocalModel>(
    _entities[3].properties[3],
  );

  /// See [CartProductLocalModel.cart].
  static final cart =
      obx.QueryRelationToOne<CartProductLocalModel, CartLocalModel>(
        _entities[3].properties[4],
      );
}
